### ISSUE TITLE
Basic guidance on usage

### ISSUE THREAD

**Issue by bgeesaman** [dev-sec/cis-kubernetes-benchmark#1]
Hi, nice work.  I was working on something similar, but now I think I can leverage this tool instead!  

Request:

Can you provide a bit more on how to invoke the checks more specifically than just "all"?
Can you provide guidance on your reference cluster that passes all the checks?

Thanks!

**Comment by rarenerd** [comment]
Hi,

I've added some additional information to the README which hopefully explains better on how to use this.

At the moment I don't know of an off-the-shelf reference implementation that passes. Both the kubeadm and Kops projects are good starting points however.
