### ISSUE TITLE
CIS Benchmark v1.3.0 has been released

### ISSUE THREAD

**Issue by tstuber** [dev-sec/cis-kubernetes-benchmark#18]
Just saw that [CIS Benchmark v1.3.0](https://www.cisecurity.org/benchmark/kubernetes/) is out. It is available for Kubernetes 1.11. 

Let me know if you need help with the implementation of this version :-)

**Comment by aaronlippold** [comment]
Can someone send me the XLS, XCCDF and OVAL for this and I can help.

**Comment by rarenerd** [comment]
I'm working on implementing benchmark 1.4.0 in the [version-1.4.0](https://github.com/dev-sec/cis-kubernetes-benchmark/tree/version-1.4.0) branch.

I'm afraid I'm not allowed to share the benchmark documents, you need a CIS Membership for this to download these from their website.

**Comment by rarenerd** [comment]
Profile has been updated to CIS benchmark v1.4.0.
