### ISSUE TITLE
Provide Changelog

### ISSUE THREAD

**Issue by ronlipke** [dev-sec/cis-kubernetes-benchmark#2]
Hello and thanks for making this available!

Would definitely love to see a CHANGELOG.md.  I understand the README declares the current CIS benchmark, but a changelog would be helpful for high level progress without digging into individual commits.

Thanks.

**Comment by atomic111** [comment]
@ronlipke yes you are right. we will work on this

**Comment by rarenerd** [comment]
We use https://github.com/skywinder/Github-Changelog-Generator now to automatically generate the CHANGELOG, and actually updated for what's in the repo now.

This will be fairly high level in the sense that we won't log updates to individual CIS controls. For those you'll have to look at the benchmarks themselves.
