### ISSUE TITLE
support for hyperkube

### ISSUE THREAD

**Issue by antoniobeyah** [dev-sec/cis-kubernetes-benchmark#3]
Thanks for putting this project together- are there any plans to support for testing [hyperkube](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/README.md) based deployments?

**Comment by atomic111** [comment]
@antoniobeyah not now. but PRs are welcome

**Comment by rarenerd** [comment]
I expect this works with the latest version of the profile, as long as the individual components are listed in the process list (which should happen).

If it doesn't, please feel free to open an issue with specific error messages and details of your deployment so we can look into those.
