### ISSUE TITLE
CIS Benchmark v1.2.0 has been released

### ISSUE THREAD

**Issue by erickt** [dev-sec/cis-kubernetes-benchmark#4]
I just noticed that 1.2.0 was released last week. You can find it [here](https://www.cisecurity.org/benchmark/kubernetes/). It looks like it supports Kubernetes 1.8.

**Comment by rarenerd** [comment]
It took a while but I've just updated the profile for 1.2.0. I've been looking at 1.3.0 but will wait for it to be officially published.
